### ISSUE TITLE
Update version on ankiweb

### ISSUE THREAD

**Issue by LukeLR** [LukeLR/Send-Audio-Clips-From-Audacity-To-Addcards-Ankidacity-fork#1]
Hi @ijgnd,
I hope you get a notification for this, as I don't know how to contact you otherwise. I have added m4a support and support for custom ffmpeg options to your ankidacity fork in 78a5e4ee78418761f76250d23528c5c575ad7045, but your [git repository](https://github.com/ijgnd/anki21__Send_Audio_Clips_From_Audacity_To_Addcards_Ankidacity_fork) linked on [ankiweb](https://ankiweb.net/shared/info/1326170847) returns in a 404. Was it moved or should I upload a new copy of this to ankiweb?

Cheers,
LukeLR

**Comment by ijgnd** [comment]
HI LukeLR,

I changed the visibility of most of my anki addon github repos because I regularly forget to push local changes to github and I don't want others to start their fork on a dated version.

I can apply your commit and update my ankiweb listing, probably this weekend. I guess it's better to have just one version on ankiweb.

I'd like to list where this add-on is known to work on ankiweb. What's your OS and Anki version?

Thanks for making this add-on better.

**Comment by LukeLR** [comment]
Hi ijgnd,

Awesome, thanks for getting back to me! I totally agree, having just one version on ankiweb is preferable, I just wasn't sure if you were still keeping yours around :)

I'm using Arch Linux with Qt6 and Anki 2.1.60.

Thanks,

LukeLR

**Comment by ijgnd** [comment]
I just updated the ankiweb listing at https://ankiweb.net/shared/info/1326170847

Could you try out the new version and let me know if it works for you? Thanks. I also made some other small changes.

**Comment by LukeLR** [comment]
I tested it, worked for me! Thanks for integrating my changes :)
